site_name: LilithOSi
site_url: https://solarkhan.github.io/LilithOSi/
docs_dir: "@docs"
nav:
  - Home: index.md
  - Divine Law: COVENANT.md
theme:
  name: mkdocs
extra:
  banner:
    title: Solar Khan Sigil
    watermark: Codex
